### ISSUE TITLE
[Issue] update to angular 6.1.8

### ISSUE THREAD

**Issue by BzenkoSergey** [yp2/ngx-cron-jobs#27]
Hi team,

I have faced issue with updating my project to angular 6.1.8

```
ERROR in ./node_modules/ngx-cron-jobs/ngx-cron-jobs.es5.js 37:9
Module parse failed: Identifier '__extends' has already been declared (37:9)
You may need an appropriate loader to handle this file type.
|     return extendStatics(d, b);
```

**The problem is in file "ngx-cron-jobs.es5"**
```
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
```

**My package.json**
```
"dependencies": {
    "@angular/animations": "6.1.8",
    "@angular/cdk": "6.4.7",
    "@angular/common": "6.1.8",
    "@angular/compiler": "6.1.8",
    "@angular/core": "6.1.8",
    "@angular/flex-layout": "6.0.0-beta.18",
    "@angular/forms": "6.1.8",
    "@angular/http": "6.1.8",
    "@angular/material": "6.4.7",
    "@angular/material-moment-adapter": "6.4.7",
    "@angular/platform-browser": "6.1.8",
    "@angular/platform-browser-dynamic": "6.1.8",
    "@angular/router": "6.1.8",
    "@angular/service-worker": "6.1.8",
    "@okta/okta-angular": "1.0.3",
    "body-parser": "1.18.3",
    "compression": "1.7.3",
    "core-js": "2.5.7",
    "cronstrue": "1.51.0",
    "expose-loader": "0.7.5",
    "express": "4.16.3",
    "fs": "0.0.1-security",
    "hammerjs": "2.0.8",
    "https": "1.0.0",
    "newrelic": "4.8.1",
    "ngx-cron-jobs": "6.4.9",
    "ngx-material-timepicker": "2.6.0",
    "path": "0.12.7",
    "rxjs": "6.3.2",
    "rxjs-compat": "6.3.2",
    "ngx-uploader": "6.0.4",
    "tls": "0.0.1",
    "winston": "3.1.0",
    "winston-daily-rotate-file": "3.3.2",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "6.2.3",
    "@angular/compiler-cli": "6.1.8",
    "@angular/language-service": "6.1.8",
    "@types/adal-angular": "1.0.1",
    "@types/jasmine": "2.8.8",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "10.10.1",
    "@types/validator": "9.4.2",
    "validator": "10.7.1",
    "codelyzer": "4.4.4",
    "jasmine-core": "3.2.1",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "3.0.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "2.0.4",
    "karma-jasmine": "1.1.2",
    "karma-jasmine-html-reporter": "1.3.1",
    "protractor": "5.4.1",
    "ts-node": "7.0.1",
    "tslint": "5.11.0",
    "typescript": "2.9.2",
    "@angular-devkit/build-angular": "0.8.3",
    "express-http-proxy": "1.4.0"
  }
```

**Comment by rvalenciano** [comment]
I can take a look this weekend.

**Comment by aaronbach** [comment]
@BzenkoSergey do you found a workaround for this? I'm looking for this, too.

**Comment by markoj21** [comment]
> @BzenkoSergey do you found a workaround for this? I'm looking for this, too.

The workaround is to delete the following file in the source ngx-cron-jobs.es5.js this forces npm to use ngx-cron-jobs.js and the code compiles correctly.

**Comment by rvalenciano** [comment]
Sorry, have been out of work these weeks, is this solved or we need a new fix @markoj21 @aaronbach ???

**Comment by aaronbach** [comment]
The Workaround is working, but deleting a file in the `node_modules`-folder is no adequate fix.
So we need a fix. At the moment I'm deleting the file through a npm `postinstall`-script.

**Comment by Viniukov** [comment]
@rvalenciano any news? It would be really great to make some fix

**Comment by kadosh1000** [comment]
Having the same issue using angular 7.2.3  and ngx-cron-jobs 7.2.4

**Comment by jacobsome** [comment]
Is this issue has been fixed, I am looking forward as well.
`ERROR in ./node_modules/ngx-cron-jobs/ngx-cron-jobs.es5.js 37:9
Module parse failed: Identifier '__extends' has already been declared (37:9)
You may need an appropriate loader to handle this file type.
|     return extendStatics(d, b);
| };
> function __extends(d, b) {
|     extendStatics(d, b);
|     function __() { this.constructor = d; }`

**Comment by swisscoder** [comment]
guess it's still not fixed. Unluckily simply deleting the file  ngx-cron-jobs.es5.js didnt do the job, as its referenced from  somewhere. Can someone here do a fix for specific versions? else I consider creating a new version for angular>6 from the original source.

**Comment by tania-mel** [comment]
@rvalenciano Faced the same issue, maybe you found a solution already?

**Comment by VLEFF** [comment]
Same issue, any news?

**Comment by yp2** [comment]
#29 Should fix problem. To build version 6.4.9 was used old ng-packager. New version is in npm - 6.4.10 should resolve this issue.
